sudo: required
dist: bionic
language: ruby
rvm:
  - 2.5
  - 2.6
  - 2.7

script:
  - bundle install
  - make run-rspec

after_success:
  - DEEPSOURCE_DSN=$PROD_DSN
  - echo $DEEPSOURCEDSN
  - make report-artifacts
